language: groovy
dist: trusty

os: linux

before_install:
  - wget http://services.gradle.org/distributions/gradle-5.6-bin.zip
  - unzip -qq gradle-5.6-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.6
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

jdk:
  - openjdk8
  - openjdk9

script:
  - gradle check